### PR TITLE
Fixed bug

### PR DESCRIPTION
**Pull request by justdvl**
extractor.py:
Fixed the bug realted to changes in Instagram that prevented the script from running.
Fixed the pictures scrapping alghoritm to get more than 30 pictures.
Script is working now as supposed to.
Script is now also informing user about a progress, for example  

35 / 39

Scrapping link:  https://www.instagram.com/p/.....

I changed time and headless seetings in crawl_profile.py but don't need to pull this.

### CODE REVIEW

**Comment by justdvl** [comment]
Also added bio for the profile and datetime for each post

**Comment by deniskrafczyk** [comment]
Thank you so much for your effort, but im getting this error: (using it on pi3)

Traceback (most recent call last):
  File "crawl_profile.py", line 18, in <module>
    browser = webdriver.Chrome('./assets/chromedriver', chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.33 (undefined),platform=Linux 4.9.59-v7+ armv7l)

**Comment by justdvl** [comment]
And was it working before to you? Did you try getting new version of Chromedriver?
I didn't made any changes on that level, and scrip works fine for me, so not sure if I caused your problem.

**Comment by deniskrafczyk** [comment]
Hm it never worked before. i was just getting the "-only few posts" error.
Can u tell me me what version you using? or can you upload the chromedriver?

**Comment by justdvl** [comment]
Win10:
[ChromeDriver 2.36](https://sites.google.com/a/chromium.org/chromedriver/downloads)
Google Chrome Version 65.0.3325.162 (Official Build) (64-bit)

I included the chromedriver. 
I don't know how I can help you, as I am beginner in this, but You can just look at the difference between my code and previous code and change the parts I changed in your code - maybe this way it will work.
I tested it on several profiles, last one having over thousand posts, and it works perfectly.

[chromedriver.zip](https://github.com/timgrossmann/instagram-profilecrawl/files/1819928/chromedriver.zip)

**Comment by deniskrafczyk** [comment]
Dude, it was the chromedriver. Thank you very much. Thanks for helping me to find a solution to this error and for making bugfixes and implement new features.

**Comment by justdvl** [comment]
Happy it works. Let me know if you want to add more features :D

**Comment by timgrossmann** [comment]
@justdvl This is awesome! Thank you very much.
Could you please remove the chromedriver? It's different for every system.

What you can do to keep the assets folder is just create an empty file and call it
.gitkeep
this will still push the assets folder but makes people able to put in the chrome driver for their system

Thank you very much for contributing

**Comment by justdvl** [comment]
I included chromedriver by accident. Now I don't know how to remove it.

**Comment by timgrossmann** [comment]
@justdvl No worries. 
Might still be a good idea to add the assets folder by adding a .gitkeep file and pushing it again.
Looks like sometimes have a hard time figuring out where to put the chromedriver if the assets folder is not there from the beginning

**Comment by timgrossmann** [comment]
@justdvl Thank you very much for the fix!

**Pull request merged**
