### PR TITLE
Modularize the code into classes

### PR DESCRIPTION
**Pull request by prafulfillment**
I modularized the code a few different ways: 
1. Made classes for InstagramUser & InstagramPost
2. Created SetupBrowserEnvironment so setup & teardown can occur with ContextManager
3. Login with cookies now 
4. Broke out large functions into smaller, easier to work on functions
5. Added a new sample file to take advantage of the new code 

Logic updates: 
1. Fixed an issue with views & comment counting (after Instagram updated their DOM) 

Smaller updates: 
1. Changed prints to Logger statements 
2. Used Python3 formatted strings (makes strings easier to read) 
3. Added [pipenv](https://pipenv.readthedocs.io/en/latest/) which manages pip & virtualenv conveniently

This helped me during development, but might need to be added back: 
1. Removed some exception handling so it could propagate up so I could look through the traceback
2. Removed logging from removing exception handling (could have re-raised but I liked how it looks now)

### CODE REVIEW

**Comment by timgrossmann** [comment]
@prafulfillment Just had a glance over the code and it looks much better now, thank you very much for all the updates and improvements! 😊 

Regarding your two "This helped me during development" points, I think taking into account that this tool needs some knowledge to use anyway, we should be fine in having it that way. Probably also makes it easier to report issues if the tracebacks are more descriptive.

Thank you very much!

**Comment by prafulfillment** [comment]
This is a fantastic project and saved me so much time so wanted to contribute some of my changes back :) 

I looked at your other projects and they're fantastic, if you could help point me in the direction for getting the chromedriver pip package setup I can add it in.

**Comment by prafulfillment** [comment]
Also just noticed I kept some libraries that are unnecessary (was using them for a client project) like Flask, Gunicorn, arrow. Will remove them in the next push 🤦‍♂

**Comment by timgrossmann** [comment]
@prafulfillment Awesome! Really appreciate it and am glad they helped and saved you time 😄 

Here's the repository of @breuerfelix which he created for InstaPy 😊 
https://github.com/breuerfelix/chromedriver-py

**Pull request merged**
