### PR TITLE
check & init chromedriver

### PR DESCRIPTION
**Pull request by timmoh**

### CODE REVIEW

**Comment by justdvl** [comment]
What is this doing?

**Comment by timmoh** [comment]
@justdvl  see above (just edited)

**Comment by justdvl** [comment]
Oh ok. I thought it could also auto download Chromedriver.
BTW I wonder, is there a way to add this script, or Instapy to npm library, to have it maintained automatically?

**Comment by timmoh** [comment]
that would be nice but i think instapy has a lot of overhead for this project

**Pull request merged**
