### PR TITLE
Added follower list feature

### PR DESCRIPTION
**Pull request by astu9880**
Solves issue #82.
Run 
`python crawl_followers.py {{target_user_id}}` 
after providing username password in utils.settings.
Saves a list of user_ids in file `./followers/{target_user_id}_followers.txt`

### CODE REVIEW

**Comment by astu9880** [comment]
@timgrossmann Can you proof check the code?
Currently doesn't work for very large number of followers because of instagram's graph api's rate limit.

**Comment by timmoh** [comment]
@astu9880 Wouldn't json be a better output format? in my opinion it would be great to use the standard output json so that we don't get 3 file per crawl

**Comment by timmoh** [comment]
Why don't you use the standard output file?

./profiles/{username}.json
```
{
  "alias": "Tim Gro\u00dfmann",
  "username": "grossertim",
  "num_of_posts": 127,
  "followers": {
        "count": 1111,
        "list": [
          {
               "user1",
               "user2",
               "user3"
           },
         ],
}
```

**Comment by imansh77** [comment]
@astu9880 providing result in JSON is definitely a better idea for further usage, I agree with @timmoh

**Comment by astu9880** [comment]
The way I see this can be done is using a temporary file as an intermediate. We then add data to the mentioned json using the intermediate temp file after fetching the complete list. Storing a list of followers in memory makes the script much slower. Does the former implementation sound reasonable? @timmoh @imansh77 @timgrossmann

**Comment by timgrossmann** [comment]
@astu9880 Thank you very much for the explanation.

@timmoh @imansh77 You guys are doing most of the development here so it's your call.
If you think this has to be done with JSON let's stick to this.

@astu9880 Could you refactor your PR to resemble the JSON-Approach, please?

**Comment by imansh77** [comment]
@astu9880 I'm sorry I don't get your point about saving in a temporary file, after running the "crawl_followers.py" it should generate a file and right now it's doing it by generating a .txt file, we suggest that instead of .txt file return the followers list in a standard JSON file, now correct me if I'm wrong. @timgrossmann @timmoh are we in a same page? or you mean something else?

**Comment by dkbast** [comment]
@imansh77 @timgrossmann @timmoh 
the way it is setup right now is actually super useful. Just as with the commenters.txt this allows for easy piping (feeding the followers back into the script). What I would suggest are two things: 
1) There should be a single file json output including commenters etc which can be loaded into mongo for better querying
2) There should be a bash-friendly multi-file option. The followers.txt file is put in the same directory as the profile.json and commenters.txt 
Both options should be available to suit both needs: 
The database for data mining as well as the text files for automated bash workflow.

**Comment by timmoh** [comment]
refactored it into json output => see #128

**Comment by timgrossmann** [comment]
@astu9880 Thank you very much for this PR, as @timmoh mentioned we'll use JSON output in this tooling.

@timmoh Thank you for refactoring it

**Comment by masudr4n4** [comment]
Hi all!
seems follower limit is not working.
i set the limit_amount = 10
but it scraped 1800+ follower.
is it happening to all?

**Comment by liyunrui** [comment]
@masudr4n4 hi, I think limit_amount is only related to number of post you scraped. It has nothing to do with followers.
@timmoh Hi, may I know why I number of followers is not same as length of list representing followers? or anyone know what's wrong

**Comment by timmoh** [comment]
> limit_amount is only related to number of post

that's right


> number of followers is not same as length of list representing

when the script crashes or get blocked by instragram because of heavy the scripts stops at this point, so the followerslist maybe smaller than the follower count

**Pull request closed without merging**
