### PR TITLE
scrap users who liked post

### PR DESCRIPTION
**Pull request by timmoh**
Should the users who liked the post saved in json files
**Attention:** be aware it would take a lot of time. script just can load 12 like at once. before making a break and load again
```python
Settings.scrap_posts_likers = True
```

output in json:

```json
"likes": {
                "count": 1234,
                "list": [
                    "username1",
                    "username2",
                    "username3"]
            },
```

### CODE REVIEW

**Comment by timgrossmann** [comment]
@timmoh Great addition! Thank you

Maybe can quickly test if it's working correctly and approve it @justdvl

**Comment by justdvl** [comment]
Hey guys I have some problems here. 
First of all, Instagram is not allowing my script to log in, saying it is suspicious activity. I wrote a bunch of coude to handle this for user, and loging with cookies after first manual login seems like a best idea.
Also logginig in should be slower, maybe that's why Instagram started banning me. No user can click and type that fast.
Second of all, I don't think we should be getting all the comments.. Some posts have too much. There should be limit, like I added origially, to only get first 200 comments and commenters and than move on.

**Comment by justdvl** [comment]
@timmoh I have cloned a brand new clone with this PR, it works well without a login, but when I put login and password (to get likes)(and disable headless because otherwise Instagram won't let me in), I get 
> `Could not get information from post:`
error.
Does this work for you? Where might be a problem?

**Comment by timmoh** [comment]
mmh I don't you this login function because you could be logged out...
haven't changed anything on the get info this. just add the feature to get all the users who liked it

> Hey guys I have some problems here.
> First of all, Instagram is not allowing my script to log in, saying it is suspicious activity. I wrote a bunch of coude to handle this for user, and loging with cookies after first manual login seems like a best idea.
> Also logginig in should be slower, maybe that's why Instagram started banning me. No user can click and type that fast.
> Second of all, I don't think we should be getting all the comments.. Some posts have too much. There should be limit, like I added origially, to only get first 200 comments and commenters and than move on.

but this seems to be a problem with the login function not with this function where you get the users who liked a post.
I don't want a ban so I never login if I scrap instagram

**Comment by justdvl** [comment]
Yea I have separated account to test these kind of things.
Anyway, I managed to logged in via this script, but after login, the _Could not get information from post:_ errors pop out from the script.
That's why my second message: Does this pull request actually work for you? Because for me it doesnt.

**Comment by justdvl** [comment]
I tested it again, on new computer with new installation. When login credentials are inputted, script throws error for every post and nothing is scrapped..

**Comment by timmoh** [comment]
ok I've checked it and rebuild the error. It is not an error in this pull it's a general error when your are logged in and an instafriend liked the post you want to scrap

**Pull request merged**
