### PR TITLE
Some changes I made working for my brother's bachelor thesis

### PR DESCRIPTION
**Pull request by noiob**
As discussed, here's the usable part of the work I did for my brother's bachelor thesis. Thanks for your help!

### CODE REVIEW

**Comment by timgrossmann** [comment]
@noiob Awesome, thank you very much for your PR 😊

**Comment by timgrossmann** [comment]
Since this will break compatibility with older json files, we should maybe wait for 1-2 people to have looked at this.

@timmoh what do you think about this?

**Comment by timmoh** [comment]
@timgrossmann sry I'm on vacation. Perhaps someone else is possible to look at it

**Comment by timgrossmann** [comment]
@timmoh No worries, there's no hurry with this one.
Just some general improvements.

Thank you for your quick response though! 😊

**Pull request merged**
