### PR TITLE
adding login feature and fixing issues #28 and #108 

### PR DESCRIPTION
**Pull request by imansh77**
this is a major changing, I want to add more features therefor I needed to implement the constructor layer(logging). crawler_profile has minor changes but an important one (save cache), in order to get username and password I changed cli_helper but this changed the behavior of accepting inputs(it won't get multiple usernames at same time which in my opinion is useless) and the most important part is extractor which I added login function to it. Thanks for your patience, with all respect.

### CODE REVIEW

**Comment by timmoh** [comment]
Hey @imansh77 I cannot merge this request, this would break every installation of instagram profilecrawl. you changed the complete behavior from calling the script with serval usernames to a script with just one username...
Please rewrite your code so the user login is optional. 
perhaps by putting the user/pw settings into the script like Instapy does it....

**Comment by timgrossmann** [comment]
@imansh77 @timmoh I think the changes are pretty nice. 
Maybe we can create a new branch for this to start developing a "new" version that introduces the login with this PR.
At one point, we could switch the master to the login approach and keep the old version for "legacy" support

**Comment by imansh77** [comment]
@timgrossmann yeah in my opinion its better to have new branch because next features need to log in so it cant be optional and on the other hand some people may not want to enter their user & pass (even we do not have any option to save theirs but anyway) so they can use the "legacy" version.

**Comment by timmoh** [comment]
@imansh77 @timgrossmann 
What about the option with put the credentials into the start script oder settings.py?
That would keep the old ones functional and opens use the possibilty to login

settings.py
```
class Settings:
    #True = login to instagram, default is False
    use_logincredentials = False 

```
crawl_profile.py
```
...
Settings.use_logincredentials = True
login_username = 'xxx'
login_passwort = 'xxx'
```

**Comment by justdvl** [comment]
I don't see a reason to create a new branch, if all we need login for is to
get number of likes?
It is very easy to set it up as optional feature, I.e. if user fills his
username and password into crawl_profile file, script will log in and
recover likes, otherwise it will not log in and will not recover likes.

**Comment by imansh77** [comment]
Sure, no problem at all I'll work on it to make it optional.

**Comment by timgrossmann** [comment]
@timmoh Even better
@justdvl @imansh77 👍

**Comment by imansh77** [comment]
@timgrossmann @timmoh I think this one should be satisfying it gets as many username as user wants while getting user name and password is optional.

**Comment by timmoh** [comment]
@imansh77 is there a reason not using the settings inside the script? user/password on console isn't always a good idea

**Comment by imansh77** [comment]
by using settings you mean user must edit the setting file to put his/her account's user/pass?

**Comment by justdvl** [comment]
Yes. Same as in Instapy, in file quickstart.py

**Comment by imansh77** [comment]
@timmoh  @justdvl but there are some cons: 1.some may don't know how to change 2. some may don't like to change code 3. and most importantly it's not straightforward at all. Remember simple is better than complex. the whole purpose is getting some input and do the rest automatically. If it needs to edit by end user then it's not a good approach.

**Comment by justdvl** [comment]
Hello,
It's up to Tim to decide, or even better users who use this program. Good
rule of thumb is, if you don't know which variant they prefer, cather for
both :D
Hovewer I am pretty sure if someone manages to run this script, s/he also
manages to change settings file.
I dont think I would like to have to put my username and password every
time I run a script. It should be saved somewhere.
I have handled similar problem in my script once that I asked user to input
the username and password into commandline when program started, than saved
in in local file. It could also be saved using cookies.

**Comment by timgrossmann** [comment]
@justdvl I'm not sure if editing the settings.py file is the right idea, too.
It might leads to problems for users when pulling the latest version with changes in the settings file.

@imansh77 @timmoh @justdvl What do you guys think of either providing it in as cl arguments or otherwise it will check the environment for the username and password (so you set it as an environment variable if you want to have it available every run without providing it).
If there is no environment set, we just use a session without login.

What do you think?

**Comment by timmoh** [comment]
in my opinion the solution with a default value in settings and editing the user and behavior (if with login or without). But I agree with the majority
@imansh77 haven't checked it now: but it seems there is a error if you one or more ":" in your password... (or if've just have a wrong interpretation of the code :-) )

**Comment by imansh77** [comment]
@timgrossmann by quoting from zen of python "There should be one-- and preferably only one --obvious way to do it." according to it I personally think its better to have one way to get the job done, and if providing username and password in setting is a better way, why provide accounts should not be via setting.py and its possible by cli? but in the end, I respect other ideas and accept the final decision warmly.
@timmoh I'm sorry I don't get your point? you mean what if we have two ":"? the user must provide in the way that is set to be, otherwise it'll be chaos.

**Comment by timgrossmann** [comment]
@imansh77 @timmoh Well, seems like we found the final implementation, right? 😉 
Let's go with the settings approach then 👍

**Comment by imansh77** [comment]
@timgrossmann @timmoh so now username and password is given by settings.py hope this one be satisfying

**Comment by timgrossmann** [comment]
@imansh77 @timmoh Perfect, thank you guys very much for the work and reviews!

**Pull request merged**
